CREATE TABLE `anime` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `alias` json DEFAULT NULL,
  `poster_url` varchar(500) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `director` json DEFAULT NULL,
  `writer` json DEFAULT NULL,
  `actor` json DEFAULT NULL,
  `genre` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `language` json DEFAULT NULL,
  `release_date` varchar(100) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `total_episode` int DEFAULT NULL,
  `storyline` text,
  `score_douban` decimal(3,1) DEFAULT NULL,
  `score_imdb` decimal(3,1) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_year` (`year`),
  KEY `idx_title` (`title`(100)),
  KEY `idx_status` (`status`),
  KEY `idx_anime_year` (`year`),
  KEY `idx_anime_score_douban` (`score_douban`),
  KEY `idx_anime_updated_at` (`updated_at`),
  KEY `idx_anime_title` (`title`(20)),
  KEY `idx_deleted_created` (`is_deleted`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `content_type` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `code` varchar(20) NOT NULL,
  `sort` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `crawler_schedule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `content_type` varchar(20) NOT NULL,
  `source_site` varchar(50) NOT NULL DEFAULT '七味网',
  `enabled` tinyint NOT NULL DEFAULT '1',
  `cron_expression` varchar(50) NOT NULL DEFAULT '0 */5 * * * *',
  `batch_size` int NOT NULL DEFAULT '20',
  `rate_limit_ms` int NOT NULL DEFAULT '2000',
  `priority` varchar(20) NOT NULL DEFAULT 'by_score',
  `genre_filter` json DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'idle',
  `last_run_time` datetime DEFAULT NULL,
  `next_run_time` datetime DEFAULT NULL,
  `total_runs` int NOT NULL DEFAULT '0',
  `total_items` int NOT NULL DEFAULT '0',
  `last_crawled_page` int DEFAULT '0',
  `last_crawled_id` bigint DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_enabled` (`enabled`),
  KEY `idx_content_type` (`content_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `crawler_task_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `schedule_id` bigint unsigned DEFAULT NULL,
  `schedule_name` varchar(100) DEFAULT NULL,
  `content_type` varchar(20) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `items_crawled` int NOT NULL DEFAULT '0',
  `items_added` int NOT NULL DEFAULT '0',
  `items_updated` int NOT NULL DEFAULT '0',
  `error_message` text,
  `duration_ms` int DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `finished_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_schedule` (`schedule_id`),
  KEY `idx_status` (`status`),
  KEY `idx_started` (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `drama` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `alias` json DEFAULT NULL,
  `poster_url` varchar(500) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `director` json DEFAULT NULL,
  `writer` json DEFAULT NULL,
  `actor` json DEFAULT NULL,
  `genre` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `language` json DEFAULT NULL,
  `release_date` varchar(100) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `total_episode` int DEFAULT NULL,
  `storyline` text,
  `score_douban` decimal(3,1) DEFAULT NULL,
  `score_imdb` decimal(3,1) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_year` (`year`),
  KEY `idx_title` (`title`(100)),
  KEY `idx_status` (`status`),
  KEY `idx_drama_year` (`year`),
  KEY `idx_drama_score_douban` (`score_douban`),
  KEY `idx_drama_updated_at` (`updated_at`),
  KEY `idx_drama_title` (`title`(20)),
  KEY `idx_deleted_created` (`is_deleted`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `episode_backup` (
  `id` bigint unsigned NOT NULL DEFAULT '0',
  `content_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `content_id` bigint unsigned NOT NULL,
  `season` int NOT NULL DEFAULT '1',
  `episode_number` int NOT NULL,
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `poster_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `movie` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `alias` json DEFAULT NULL,
  `poster_url` varchar(500) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `director` json DEFAULT NULL,
  `writer` json DEFAULT NULL,
  `actor` json DEFAULT NULL,
  `genre` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `language` json DEFAULT NULL,
  `release_date` varchar(100) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `storyline` text,
  `score_douban` decimal(3,1) DEFAULT NULL,
  `score_imdb` decimal(3,1) DEFAULT NULL,
  `score_rt` decimal(3,1) DEFAULT NULL,
  `series_name` varchar(200) DEFAULT NULL,
  `series_order` int DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_year` (`year`),
  KEY `idx_title` (`title`(100)),
  KEY `idx_series` (`series_name`),
  KEY `idx_status` (`status`),
  KEY `idx_movie_year` (`year`),
  KEY `idx_movie_score_douban` (`score_douban`),
  KEY `idx_movie_score_imdb` (`score_imdb`),
  KEY `idx_movie_updated_at` (`updated_at`),
  KEY `idx_movie_title` (`title`(20)),
  KEY `idx_deleted_created` (`is_deleted`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `action` varchar(20) NOT NULL,
  `module` varchar(30) NOT NULL,
  `target` varchar(200) DEFAULT NULL,
  `detail` text,
  `ip` varchar(50) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `error_message` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_module` (`module`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_cloud` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `content_type` varchar(20) NOT NULL,
  `content_id` bigint unsigned NOT NULL,
  `disk_type` varchar(20) NOT NULL,
  `title` varchar(200) DEFAULT NULL,
  `url` text NOT NULL,
  `password` varchar(50) DEFAULT NULL,
  `sort` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_content` (`content_type`,`content_id`),
  KEY `idx_disk_type` (`disk_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_magnet` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `content_type` varchar(20) NOT NULL,
  `content_id` bigint unsigned NOT NULL,
  `title` varchar(200) DEFAULT NULL,
  `magnet_url` text NOT NULL,
  `resolution` varchar(20) DEFAULT NULL,
  `has_subtitle` tinyint NOT NULL DEFAULT '0',
  `is_special_sub` tinyint NOT NULL DEFAULT '0',
  `sort` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_content` (`content_type`,`content_id`),
  KEY `idx_resolution` (`resolution`),
  KEY `idx_subtitle` (`has_subtitle`),
  KEY `idx_special_sub` (`is_special_sub`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_online` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `content_type` varchar(20) NOT NULL,
  `content_id` bigint unsigned NOT NULL,
  `season` int DEFAULT '1',
  `episode_number` int DEFAULT NULL,
  `episode_title` varchar(200) DEFAULT NULL,
  `source_name` varchar(50) NOT NULL,
  `source_url` text NOT NULL,
  `sort` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_content` (`content_type`,`content_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_source` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `url` varchar(500) DEFAULT NULL,
  `enabled` tinyint NOT NULL DEFAULT '1',
  `sort` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `short_drama` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `alias` json DEFAULT NULL,
  `poster_url` varchar(500) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `director` json DEFAULT NULL,
  `actor` json DEFAULT NULL,
  `genre` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `language` json DEFAULT NULL,
  `release_date` varchar(100) DEFAULT NULL,
  `total_episode` int DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `storyline` text,
  `score_douban` decimal(3,1) DEFAULT NULL,
  `score_imdb` decimal(3,1) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_year` (`year`),
  KEY `idx_title` (`title`(100)),
  KEY `idx_status` (`status`),
  KEY `idx_short_drama_year` (`year`),
  KEY `idx_short_drama_score_douban` (`score_douban`),
  KEY `idx_short_drama_updated_at` (`updated_at`),
  KEY `idx_short_drama_title` (`title`(20)),
  KEY `idx_deleted_created` (`is_deleted`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `system_setting` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `description` varchar(200) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nickname` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_movie_list` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_default` tinyint DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_type` (`user_id`,`type`),
  KEY `idx_user_movie_list_user_id` (`user_id`),
  KEY `idx_user_movie_list_user_type` (`user_id`,`type`),
  CONSTRAINT `user_movie_list_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_movie_list_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `list_id` bigint NOT NULL,
  `movie_id` bigint NOT NULL,
  `content_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `added_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `rating` decimal(3,1) DEFAULT NULL,
  `note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_list_movie` (`list_id`,`movie_id`,`content_type`),
  KEY `idx_movie` (`movie_id`,`content_type`),
  KEY `idx_item_list_id` (`list_id`),
  KEY `idx_item_list_movie_type` (`list_id`,`movie_id`,`content_type`),
  KEY `idx_item_movie_type` (`movie_id`,`content_type`),
  CONSTRAINT `user_movie_list_item_ibfk_1` FOREIGN KEY (`list_id`) REFERENCES `user_movie_list` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `variety` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `alias` json DEFAULT NULL,
  `poster_url` varchar(500) DEFAULT NULL,
  `year` int DEFAULT NULL,
  `director` json DEFAULT NULL,
  `writer` json DEFAULT NULL,
  `actor` json DEFAULT NULL,
  `genre` json DEFAULT NULL,
  `region` json DEFAULT NULL,
  `language` json DEFAULT NULL,
  `release_date` varchar(100) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `total_episode` int DEFAULT NULL,
  `storyline` text,
  `score_douban` decimal(3,1) DEFAULT NULL,
  `score_imdb` decimal(3,1) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_year` (`year`),
  KEY `idx_title` (`title`(100)),
  KEY `idx_status` (`status`),
  KEY `idx_variety_year` (`year`),
  KEY `idx_variety_score_douban` (`score_douban`),
  KEY `idx_variety_updated_at` (`updated_at`),
  KEY `idx_variety_title` (`title`(20)),
  KEY `idx_deleted_created` (`is_deleted`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
